version: '2'
services:
  redis:
    image: redis
    
  nginx:
    image: nginx:latest
    container_name: Nginx01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
      - ./src/public/media:/media
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
      
  web:
    build: .
    container_name: Django-Jiller
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py loaddata project/fixtures/init_data.json && gunicorn Jiller.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
      - /static:/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Jiller worker -l info
    volumes:
      - ./src:/src
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
